--删除历史税率表
DROP TABLE rec_TaxHis;
--删除库存明细_订单商品表中的库存类型字段
ALTER TABLE "RJDS"."REC_STOCKDET_ORDERGOOD" DROP("STOCKCODE");
--修改订单_商品表
ALTER TABLE "RJDS"."REC_ORDER_GOOD"
ADD ( "AMOUNTNOTAX" NUMBER(19,2) NULL  ) ;

ALTER TABLE "RJDS"."REC_ORDER_GOOD" DROP("PRICETAX");

COMMENT ON COLUMN "RJDS"."REC_ORDER_GOOD"."PRICE" IS '含税单价';

ALTER TABLE "RJDS"."REC_ORDER_GOOD" RENAME COLUMN "PRICE" TO "PRICEHASTAX";

COMMENT ON COLUMN "RJDS"."REC_ORDER_GOOD"."UNITPRICE" IS '未税单价';

ALTER TABLE "RJDS"."REC_ORDER_GOOD" RENAME COLUMN "UNITPRICE" TO "PRICENOTAX";

COMMENT ON COLUMN "RJDS"."REC_ORDER_GOOD"."AMOUNTNOTAX" IS '未税金额';

--新增历史价格记录表
CREATE TABLE "RJDS"."rec_Price" (
"id" NUMBER(10) NOT NULL ,
"stockDetId" NUMBER(10) NOT NULL ,
"stockCode" VARCHAR2(255 BYTE) NOT NULL ,
"priceNoTax" NUMBER(19,2) NULL ,
"priceHasTax" NUMBER(19,2) NOT NULL ,
"num" NUMBER(19,3) NOT NULL ,
"affirmNum" NUMBER(19,3) NULL ,
"operationId" NUMBER(10) NULL ,
"operationIp" VARCHAR2(64 BYTE) NULL ,
"createTime" DATE DEFAULT sysdate  NULL ,
"statusCode" VARCHAR2(30 BYTE) DEFAULT '001'  NULL ,
"demo" VARCHAR2(400 BYTE) NULL
)
LOGGING
NOCOMPRESS
NOCACHE

;
COMMENT ON COLUMN "RJDS"."rec_Price"."id" IS 'ID';
COMMENT ON COLUMN "RJDS"."rec_Price"."stockDetId" IS '库存明细ID';
COMMENT ON COLUMN "RJDS"."rec_Price"."stockCode" IS '库存类型code';
COMMENT ON COLUMN "RJDS"."rec_Price"."priceNoTax" IS '未税单价';
COMMENT ON COLUMN "RJDS"."rec_Price"."priceHasTax" IS '含税单价';
COMMENT ON COLUMN "RJDS"."rec_Price"."num" IS '数量';
COMMENT ON COLUMN "RJDS"."rec_Price"."affirmNum" IS '确认数量';
COMMENT ON COLUMN "RJDS"."rec_Price"."operationId" IS '操作人ID';
COMMENT ON COLUMN "RJDS"."rec_Price"."operationIp" IS '操作人IP';
COMMENT ON COLUMN "RJDS"."rec_Price"."createTime" IS '创建时间';
COMMENT ON COLUMN "RJDS"."rec_Price"."statusCode" IS '有效状态：001=有效 002=无效';
COMMENT ON COLUMN "RJDS"."rec_Price"."demo" IS '备注';

ALTER TABLE "RJDS"."rec_Price" ADD CHECK ("id" IS NOT NULL);
ALTER TABLE "RJDS"."rec_Price" ADD CHECK ("stockDetId" IS NOT NULL);
ALTER TABLE "RJDS"."rec_Price" ADD CHECK ("stockCode" IS NOT NULL);
ALTER TABLE "RJDS"."rec_Price" ADD CHECK ("priceHasTax" IS NOT NULL);
ALTER TABLE "RJDS"."rec_Price" ADD CHECK ("num" IS NOT NULL);

ALTER TABLE "RJDS"."rec_Price" ADD PRIMARY KEY ("id");
ALTER TABLE "RJDS"."rec_Price" ADD CONSTRAINT "FK_Price_StockDet" FOREIGN KEY ("stockDetId") REFERENCES "RJDS"."REC_STOCKDET" ("ID");
--创建序列
CREATE SEQUENCE seq_rec_price INCREMENT BY 1 --每次加几
START WITH 1;

--删表 加字段
ALTER TABLE REC_COMPANY_STORAGE DROP  constraint  FK_COMPANYSTORAGE_COMPANY

ALTER TABLE REC_COMPANY_STORAGE DROP  constraint  FK_COMPANYSTORAGE_STORAGE

ALTER TABLE REC_STOCK  DROP  constraint FK_STOCK_COMPANYSTORAGE

ALTER TABLE REC_STOCK  DROP column FRONTSTOCKID

DROP TABLE  REC_COMPANY_STORAGE


ALTER TABLE REC_STOCK  add companyId  NUMBER(10)  NOT NULL

ALTER TABLE REC_STOCK  add storageId  NUMBER(10)  NOT NULL


ALTER TABLE REC_STOCK ADD  constraint FK_REC_COMPANY_REC_STOCK  FOREIGN KEY (companyId) REFERENCES REC_COMPANY(ID)

ALTER TABLE REC_STOCK ADD  constraint  FK_DIC_STORAGE_REC_STOCK  FOREIGN KEY (storageId) REFERENCES DIC_STORAGE(ID)

--改列名
alter table  rec_stockdet rename  column NUM  to INITNUM;
alter table  rec_stockdet rename  column LEFTNUM to SURPLUSNUM;