ALTER TABLE "REC_FRONTUSER" RENAME COLUMN "前台用户公司ID" TO "COMPANYID";

COMMENT ON COLUMN "DIC_AUTHBACKUSER"."ID" IS '主键';

COMMENT ON COLUMN "DIC_AUTHBACKUSER"."PARENTID" IS '父菜单';

COMMENT ON COLUMN "DIC_AUTHBACKUSER"."NAME" IS '名称';

COMMENT ON COLUMN "DIC_AUTHBACKUSER"."LEVELCODE" IS '层级码，实现后台权限的树形管理';

COMMENT ON COLUMN "DIC_AUTHBACKUSER"."POSITION" IS '位置，左侧菜单栏的顺序';

COMMENT ON COLUMN "DIC_AUTHBACKUSER"."URL" IS 'URL';

COMMENT ON COLUMN "DIC_AUTHBACKUSER"."MATCHURL" IS '匹配URL';

COMMENT ON COLUMN "DIC_AUTHBACKUSER"."ICON" IS '图标URL';

COMMENT ON COLUMN "DIC_AUTHBACKUSER"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "DIC_AUTHBACKUSER"."MEMO" IS '备注';

COMMENT ON COLUMN "DIC_AUTHFRONTUSER"."NAME" IS '名称：上架、下架、修改价格、评论';

COMMENT ON COLUMN "DIC_AUTHFRONTUSER"."PARENTID" IS '父菜单';

COMMENT ON COLUMN "DIC_AUTHFRONTUSER"."ORD" IS '顺序号：对同一层级的项进行排序';

COMMENT ON COLUMN "DIC_AUTHFRONTUSER"."LEVELCODE" IS '层级码：实现前台权限的树形管理';

COMMENT ON COLUMN "DIC_AUTHFRONTUSER"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "DIC_AUTHFRONTUSER"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "DIC_AUTHFRONTUSER"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "DIC_AUTHFRONTUSER"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "DIC_AUTHFRONTUSER"."MEMO" IS '备注';

COMMENT ON COLUMN "DIC_DIC"."ID" IS '主键';

COMMENT ON COLUMN "DIC_DIC"."TYPEID" IS '类型ID';

COMMENT ON COLUMN "DIC_DIC"."NAME" IS '名称';

COMMENT ON COLUMN "DIC_DIC"."SHORTNAME" IS '简称，部分字典项有效';

COMMENT ON COLUMN "DIC_DIC"."PARENTID" IS 'PID';

COMMENT ON COLUMN "DIC_DIC"."ORD" IS '顺序号，对同一层级的项进行排序';

COMMENT ON COLUMN "DIC_DIC"."LEVELCODE" IS '层级码，在业务表中存储的是层级码';

COMMENT ON COLUMN "DIC_DIC"."URL" IS 'URL，部分字典项有效';

COMMENT ON COLUMN "DIC_DIC"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "DIC_DIC"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "DIC_DIC"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "DIC_DIC"."STATUSCODE" IS '有效状态，001=有效 002=无效';

COMMENT ON COLUMN "DIC_DIC"."MEMO" IS '备注';

COMMENT ON COLUMN "DIC_DICTYPE"."ID" IS '主键';

COMMENT ON COLUMN "DIC_DICTYPE"."NAME" IS '名称';

COMMENT ON COLUMN "DIC_DICTYPE"."ENG" IS '英文名';

COMMENT ON COLUMN "DIC_DICTYPE"."ORD" IS '顺序号，对同一层级的项进行排序';

COMMENT ON COLUMN "DIC_DICTYPE"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "DIC_DICTYPE"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "DIC_DICTYPE"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "DIC_DICTYPE"."STATUSCODE" IS '有效状态，001=有效 002=无效';

COMMENT ON COLUMN "DIC_DICTYPE"."MEMO" IS '备注';

COMMENT ON COLUMN "DIC_FARE"."ID" IS '主键';

COMMENT ON COLUMN "DIC_FARE"."GOODKINDCODE" IS '品种code，不同品种的商品，运费标准可能不同';

COMMENT ON COLUMN "DIC_FARE"."CODENO" IS '编号';

COMMENT ON COLUMN "DIC_FARE"."NAME" IS '线路';

COMMENT ON COLUMN "DIC_FARE"."MEACODE" IS '计量单位code：001=克，002=千克，003=吨';

COMMENT ON COLUMN "DIC_FARE"."FAREPER" IS '运费单价：里程与重量，例如：1吨*公里';

COMMENT ON COLUMN "DIC_FARE"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "DIC_FARE"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "DIC_FARE"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "DIC_FARE"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "DIC_FARE"."MEMO" IS '备注';

COMMENT ON COLUMN "DIC_GOOD"."ID" IS '主键';

COMMENT ON COLUMN "DIC_GOOD"."MARK" IS '牌号';

COMMENT ON COLUMN "DIC_GOOD"."GOODKINDCODE" IS '品种code：001=PE，002=PP，003=PVC，其中001001=HDPE，001001001=薄膜';

COMMENT ON COLUMN "DIC_GOOD"."MEACODE" IS '计量单位code：001=克，002=千克，003=吨';

COMMENT ON COLUMN "DIC_GOOD"."USECODE" IS '用途级别code：001=薄膜级，002=电子电器部件';

COMMENT ON COLUMN "DIC_GOOD"."MACCODE" IS '加工级别code';

COMMENT ON COLUMN "DIC_GOOD"."GOODTYPECODE" IS '商品分类code：用于大数据分析';

COMMENT ON COLUMN "DIC_GOOD"."PICURL" IS '图片url';

COMMENT ON COLUMN "DIC_GOOD"."CONTENT" IS '描述';

COMMENT ON COLUMN "DIC_GOOD"."RATE" IS '税率：平台定义的标准税率，规则未知';

COMMENT ON COLUMN "DIC_GOOD"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "DIC_GOOD"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "DIC_GOOD"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "DIC_GOOD"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "DIC_GOOD"."MEMO" IS '备注';

COMMENT ON COLUMN "DIC_ORG"."ID" IS '主键';

COMMENT ON COLUMN "DIC_ORG"."PARENTID" IS 'PID';

COMMENT ON COLUMN "DIC_ORG"."NAME" IS '机构名称';

COMMENT ON COLUMN "DIC_ORG"."CODENO" IS '编号';

COMMENT ON COLUMN "DIC_ORG"."LEVELCODE" IS '层级码：实现机构的树形管理';

COMMENT ON COLUMN "DIC_ORG"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "DIC_ORG"."MEMO" IS '备注';

COMMENT ON COLUMN "DIC_ROLE"."ID" IS '主键';

COMMENT ON COLUMN "DIC_ROLE"."CODENO" IS '编码';

COMMENT ON COLUMN "DIC_ROLE"."NAME" IS '角色名';

COMMENT ON COLUMN "DIC_ROLE"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "DIC_ROLE"."MEMO" IS '备注';

COMMENT ON COLUMN "DIC_STORAGE"."ID" IS '主键';

COMMENT ON COLUMN "DIC_STORAGE"."CODENO" IS '编号';

COMMENT ON COLUMN "DIC_STORAGE"."PROVCODE" IS '省code';

COMMENT ON COLUMN "DIC_STORAGE"."CITYCODE" IS '市code';

COMMENT ON COLUMN "DIC_STORAGE"."COUNTYCODE" IS '县code(具体位置可能没有县)';

COMMENT ON COLUMN "DIC_STORAGE"."ADDRESS" IS '详细地址';

COMMENT ON COLUMN "DIC_STORAGE"."POSTAL" IS '邮编';

COMMENT ON COLUMN "DIC_STORAGE"."LINKMAN" IS '联系人（仓储人员不是前台用户）';

COMMENT ON COLUMN "DIC_STORAGE"."MOBPHONE" IS '手机';

COMMENT ON COLUMN "DIC_STORAGE"."PHONE" IS '固话';

COMMENT ON COLUMN "DIC_STORAGE"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "DIC_STORAGE"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "DIC_STORAGE"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "DIC_STORAGE"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "DIC_STORAGE"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_ADDRESS"."ID" IS '主键';

COMMENT ON COLUMN "REC_ADDRESS"."FRONTUSERID" IS '前台客户ID';

COMMENT ON COLUMN "REC_ADDRESS"."CODENO" IS '编号';

COMMENT ON COLUMN "REC_ADDRESS"."ADDRESS" IS '详细地址';

COMMENT ON COLUMN "REC_ADDRESS"."POSTAL" IS '邮编';

COMMENT ON COLUMN "REC_ADDRESS"."LINKMAN" IS '联系人';

COMMENT ON COLUMN "REC_ADDRESS"."MOBPHONE" IS '手机';

COMMENT ON COLUMN "REC_ADDRESS"."PHONE" IS '固话';

COMMENT ON COLUMN "REC_ADDRESS"."ADDRDEFAULTCODE" IS '默认地址code：001=默认 002=非默认';

COMMENT ON COLUMN "REC_ADDRESS"."PROVCODE" IS '省code';

COMMENT ON COLUMN "REC_ADDRESS"."CITYCODE" IS '市code';

COMMENT ON COLUMN "REC_ADDRESS"."COUNTYCODE" IS '县code(具体位置可能没有县)';

COMMENT ON COLUMN "REC_ADDRESS"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_ADDRESS"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_ADDRESS"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_ADDRESS"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_ADDRESS"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_ANNEX"."ID" IS '主键';

COMMENT ON COLUMN "REC_ANNEX"."GUESTID" IS '前台用户ID：guestId';

COMMENT ON COLUMN "REC_ANNEX"."ANNEXCODE" IS '附件类型code：001=营业执照，002=组织机构代码证，...';

COMMENT ON COLUMN "REC_ANNEX"."CHARTERURL" IS '附件路径';

COMMENT ON COLUMN "REC_ANNEX"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_ANNEX"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_ANNEX"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_ANNEX"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_ANNEX"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_AUTH_FRONTUSER"."ID" IS '主键';

COMMENT ON COLUMN "REC_AUTH_FRONTUSER"."GUESTID" IS '前台用户ID';

COMMENT ON COLUMN "REC_AUTH_FRONTUSER"."AUTHFRONTUSERID" IS '前天权限ID';

COMMENT ON COLUMN "REC_AUTH_FRONTUSER"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_AUTH_FRONTUSER"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_AUTH_FRONTUSER"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_AUTH_FRONTUSER"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_AUTH_FRONTUSER"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_BACKUSER"."ID" IS '主键';

COMMENT ON COLUMN "REC_BACKUSER"."ROLEID" IS '角色ID';

COMMENT ON COLUMN "REC_BACKUSER"."UNITID" IS '机构ID';

COMMENT ON COLUMN "REC_BACKUSER"."LOGIN" IS '登录名';

COMMENT ON COLUMN "REC_BACKUSER"."PASSWORD" IS '密码';

COMMENT ON COLUMN "REC_BACKUSER"."NAME" IS '姓名';

COMMENT ON COLUMN "REC_BACKUSER"."CODENO" IS '员工编号：自动生成规则未知';

COMMENT ON COLUMN "REC_BACKUSER"."IC" IS '身份证号';

COMMENT ON COLUMN "REC_BACKUSER"."EMAIL" IS '邮箱';

COMMENT ON COLUMN "REC_BACKUSER"."REGTIME" IS '注册时间';

COMMENT ON COLUMN "REC_BACKUSER"."BEGINTIME" IS '开始时间';

COMMENT ON COLUMN "REC_BACKUSER"."ENDTIME" IS '结束时间';

COMMENT ON COLUMN "REC_BACKUSER"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_BACKUSER"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_BANKFRONTUSER"."ID" IS '主键';

COMMENT ON COLUMN "REC_BANKFRONTUSER"."COMPANYID" IS '客户公司ID';

COMMENT ON COLUMN "REC_BANKFRONTUSER"."BANKCODE" IS '开户行code：取得开户行全称';

COMMENT ON COLUMN "REC_BANKFRONTUSER"."OPERATIONIP" IS '操作的IP';

COMMENT ON COLUMN "REC_BANKFRONTUSER"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_BANKFRONTUSER"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_BANKFRONTUSER"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_BILL"."ID" IS '主键';

COMMENT ON COLUMN "REC_BILL"."ORDERID" IS '订单ID';

COMMENT ON COLUMN "REC_BILL"."FRONTUSERID" IS '买方ID';

COMMENT ON COLUMN "REC_BILL"."CODENO" IS '编号';

COMMENT ON COLUMN "REC_BILL"."TOTALMONEY" IS '价款合计（未含税）';

COMMENT ON COLUMN "REC_BILL"."TAXMONEY" IS '税额合计';

COMMENT ON COLUMN "REC_BILL"."FINALMONEY" IS '价税合计';

COMMENT ON COLUMN "REC_BILL"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_BILL"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_BILL"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_BILL"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_BILL"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_BUY"."ID" IS '主键';

COMMENT ON COLUMN "REC_BUY"."GUESTID" IS '客户ID';

COMMENT ON COLUMN "REC_BUY"."GOODID" IS '商品ID';

COMMENT ON COLUMN "REC_BUY"."CODENO" IS '编号：方便三方沟通';

COMMENT ON COLUMN "REC_BUY"."TITLE" IS '标题';

COMMENT ON COLUMN "REC_BUY"."CONTENT" IS '描述';

COMMENT ON COLUMN "REC_BUY"."LINKMAN" IS '联系人：客户联系人，不一定是登录人';

COMMENT ON COLUMN "REC_BUY"."MOBPHONE" IS '手机';

COMMENT ON COLUMN "REC_BUY"."PHONE" IS '固话';

COMMENT ON COLUMN "REC_BUY"."PRICEBEGIN" IS '出价：查账户余额，冻结，若不足提示请充值';

COMMENT ON COLUMN "REC_BUY"."PRICEPER" IS '最低加价：可选';

COMMENT ON COLUMN "REC_BUY"."PRICESUCC" IS '成交价';

COMMENT ON COLUMN "REC_BUY"."NUM" IS '数量';

COMMENT ON COLUMN "REC_BUY"."DEALCODE" IS '进展状态code：001=已发布 002=已完成 003=已取消 004=已超时';

COMMENT ON COLUMN "REC_BUY"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_BUY"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_BUY"."CREATETIME" IS '发布时间';

COMMENT ON COLUMN "REC_BUY"."UPDATETIME" IS '完成时间';

COMMENT ON COLUMN "REC_BUY"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_BUYDET"."ID" IS '主键';

COMMENT ON COLUMN "REC_BUYDET"."SELLID" IS '竞价销售ID';

COMMENT ON COLUMN "REC_BUYDET"."SUPID" IS '供应商ID';

COMMENT ON COLUMN "REC_BUYDET"."STOCKID" IS '库存ID：查库存，冻结库存数量，界面提供让卖方选择仓库、商品、批号，比对数量（不足提示）';

COMMENT ON COLUMN "REC_BUYDET"."PRICE" IS '价格';

COMMENT ON COLUMN "REC_BUYDET"."LINKMAN" IS '联系人：供应商联系人，不一定是登录人';

COMMENT ON COLUMN "REC_BUYDET"."MOBPHONE" IS '手机';

COMMENT ON COLUMN "REC_BUYDET"."PHONE" IS '固话';

COMMENT ON COLUMN "REC_BUYDET"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_BUYDET"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_BUYDET"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_BUYDET"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_BUYDET"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_CART"."ID" IS '主键';

COMMENT ON COLUMN "REC_CART"."CODENO" IS '编号';

COMMENT ON COLUMN "REC_CART"."GOODID" IS '商品ID';

COMMENT ON COLUMN "REC_CART"."NUM" IS '数量';

COMMENT ON COLUMN "REC_CART"."FRONTUSERID" IS '买方ID';

COMMENT ON COLUMN "REC_CART"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_CART"."CREATETIME" IS '创建时间：根据操作时间判断库存明细中价格等产品信息是否发生变化';

COMMENT ON COLUMN "REC_CART"."STATUSCODE" IS '有效状态：001=有效 002=购物车记录失效（信息发生变化）';

COMMENT ON COLUMN "REC_CART"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_COLLECTION"."ID" IS 'ID';

COMMENT ON COLUMN "REC_COLLECTION"."GUESTID" IS '前台用户ID：可以是买方、卖方的业务员';

COMMENT ON COLUMN "REC_COLLECTION"."VIRTUALACCOUNTID" IS '虚拟账户ID：账户属于公司的';

COMMENT ON COLUMN "REC_COLLECTION"."ORDERNUMBER" IS '收款编号';

COMMENT ON COLUMN "REC_COLLECTION"."MONEY" IS '金额';

COMMENT ON COLUMN "REC_COLLECTION"."BANKNO" IS '银行系统单号：读取银行接口';

COMMENT ON COLUMN "REC_COLLECTION"."ORDERTIME" IS '收款时间：读取银行接口';

COMMENT ON COLUMN "REC_COLLECTION"."FUNDCODE" IS '款项类型：11=正常支付 12=退款 21=保证金交纳 22=保证金释放 31=充值 32=提现';

COMMENT ON COLUMN "REC_COLLECTION"."PAYCODE" IS '支付方式（例如：002=线下支付，002001=现金、002002=电汇等）';

COMMENT ON COLUMN "REC_COLLECTION"."BACKUSERID" IS '操作人ID';

COMMENT ON COLUMN "REC_COLLECTION"."OPERATIONIP" IS '操作IP';

COMMENT ON COLUMN "REC_COLLECTION"."CREATETIME" IS '创建时间：系统自动生成';

COMMENT ON COLUMN "REC_COLLECTION"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_COMMENT"."ID" IS 'ID';

COMMENT ON COLUMN "REC_COMMENT"."ORDERGOODID" IS '订单商品ID：（例如：002=线下支付，002001=现金、002002=电汇等）';

COMMENT ON COLUMN "REC_COMMENT"."TITLE" IS '标题';

COMMENT ON COLUMN "REC_COMMENT"."CONTENT" IS '内容';

COMMENT ON COLUMN "REC_COMMENT"."STARGOODID" IS '商品星级：001=1星，002=2星，003=3星，004=4星，005=5星，';

COMMENT ON COLUMN "REC_COMMENT"."STARSELL" IS '卖家星级：001=1星，002=2星，003=3星，004=4星，005=5星，';

COMMENT ON COLUMN "REC_COMMENT"."STARSEND" IS '配送星级：001=1星，002=2星，003=3星，004=4星，005=5星，';

COMMENT ON COLUMN "REC_COMMENT"."FRONTUSERID" IS '客户ID';

COMMENT ON COLUMN "REC_COMMENT"."OPERATIONIP" IS '操作IP';

COMMENT ON COLUMN "REC_COMMENT"."CREATETIME" IS '评价时间';

COMMENT ON COLUMN "REC_COMMENT"."STATUSCODE" IS '有效状态：001=正常 002=屏蔽';

COMMENT ON COLUMN "REC_COMMENT"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_COMPANY"."ID" IS 'ID';

COMMENT ON COLUMN "REC_COMPANY"."GUESTCODE" IS '注册类型code：例如：001=买家 002=卖家';

COMMENT ON COLUMN "REC_COMPANY"."UNITNO" IS '组织机构代码';

COMMENT ON COLUMN "REC_COMPANY"."NAME" IS '公司名称';

COMMENT ON COLUMN "REC_COMPANY"."LINKMAN" IS '企业法人';

COMMENT ON COLUMN "REC_COMPANY"."PHONE" IS '固话';

COMMENT ON COLUMN "REC_COMPANY"."MOBPHONE" IS '手机';

COMMENT ON COLUMN "REC_COMPANY"."EMAIL" IS '邮箱';

COMMENT ON COLUMN "REC_COMPANY"."ADDRESS" IS '公司地址';

COMMENT ON COLUMN "REC_COMPANY"."COMPANYTYPECODE" IS '公司分类code：用于大数据分析';

COMMENT ON COLUMN "REC_COMPANY"."AFFIRMREGCODE" IS '认证状态：001=待审核 002=审核中 003=审核通过 004=审核失败';

COMMENT ON COLUMN "REC_COMPANY"."BACKUSERID" IS '业务员ID:每个后台用户负责若干前台用户';

COMMENT ON COLUMN "REC_COMPANY"."AGENTID" IS '专职经纪人ID';

COMMENT ON COLUMN "REC_COMPANY"."TAXNO" IS '税号：纳税人识别号';

COMMENT ON COLUMN "REC_COMPANY"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_COMPANY"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_COMPANY"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_COMPANY"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_COMPANY"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_COMPANY_STORAGE"."ID" IS 'ID';

COMMENT ON COLUMN "REC_COMPANY_STORAGE"."COMPANYID" IS '卖家公司ID';

COMMENT ON COLUMN "REC_COMPANY_STORAGE"."STORAGEID" IS '仓库ID';

COMMENT ON COLUMN "REC_COMPANY_STORAGE"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_COMPANY_STORAGE"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_COMPANY_STORAGE"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_COMPANY_STORAGE"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_COMPANY_STORAGE"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_FINDGOOD"."ID" IS 'ID';

COMMENT ON COLUMN "REC_FINDGOOD"."TITLE" IS '标题：首页程序不需要，客户的需求';

COMMENT ON COLUMN "REC_FINDGOOD"."CONTENT" IS '描述：客户的需求';

COMMENT ON COLUMN "REC_FINDGOOD"."LINKMAN" IS '联系人：客户联系人，不一定是登录人';

COMMENT ON COLUMN "REC_FINDGOOD"."PHONE" IS '联系方式：界面二选一，这里只保留一个';

COMMENT ON COLUMN "REC_FINDGOOD"."SUP" IS '供应商联系人：成交的供应商';

COMMENT ON COLUMN "REC_FINDGOOD"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_FINDGOOD"."OPERATIONIP" IS '操作IP：自动取得';

COMMENT ON COLUMN "REC_FINDGOOD"."DEALCODE" IS '进展状态：001=已申请 002=已完成 003=已作废（恶意） 004=已取消 005=已超时';

COMMENT ON COLUMN "REC_FINDGOOD"."BEGINTIME" IS '发布时间：以此判断失效时间';

COMMENT ON COLUMN "REC_FINDGOOD"."ENDTIME" IS '完成时间：发布请求的有效时间';

COMMENT ON COLUMN "REC_FINDGOOD"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_FRONTUSER"."ID" IS 'ID';

COMMENT ON COLUMN "REC_FRONTUSER"."COMPANYID" IS '公司ID';

COMMENT ON COLUMN "REC_FRONTUSER"."LOGIN" IS '登录名';

COMMENT ON COLUMN "REC_FRONTUSER"."PASSWORD" IS '密码';

COMMENT ON COLUMN "REC_FRONTUSER"."GUESTCODE" IS '注册类型code：例如：001=买家 002=卖家';

COMMENT ON COLUMN "REC_FRONTUSER"."UNITNO" IS '组织机构代码：应该是固定10位，尚不确定';

COMMENT ON COLUMN "REC_FRONTUSER"."COMPANY" IS '公司名称';

COMMENT ON COLUMN "REC_FRONTUSER"."NAME" IS '姓名';

COMMENT ON COLUMN "REC_FRONTUSER"."CODENO" IS '工号';

COMMENT ON COLUMN "REC_FRONTUSER"."PHONE" IS '固话';

COMMENT ON COLUMN "REC_FRONTUSER"."MOBPHONE" IS '手机';

COMMENT ON COLUMN "REC_FRONTUSER"."EMAIL" IS '邮箱';

COMMENT ON COLUMN "REC_FRONTUSER"."ADDRESS" IS '公司地址';

COMMENT ON COLUMN "REC_FRONTUSER"."AFFIRMREGCODE" IS '认证状态：三证审核 001=待审核 002=审核中 003=审核通过 004=审核失败';

COMMENT ON COLUMN "REC_FRONTUSER"."BACKUSERID" IS '业务员ID：每个后台用户负责若干前台用户';

COMMENT ON COLUMN "REC_FRONTUSER"."AGENTID" IS '专职经纪人ID';

COMMENT ON COLUMN "REC_FRONTUSER"."OPERATIONID" IS '操作人ID：后台审核人员';

COMMENT ON COLUMN "REC_FRONTUSER"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_FRONTUSER"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_FRONTUSER"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_FRONTUSER"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_GOODAPPLY"."ID" IS 'ID';

COMMENT ON COLUMN "REC_GOODAPPLY"."FRONTUSERID" IS '客户ID';

COMMENT ON COLUMN "REC_GOODAPPLY"."ORDERID" IS '订单ID';

COMMENT ON COLUMN "REC_GOODAPPLY"."STOCKID" IS '仓库ID';

COMMENT ON COLUMN "REC_GOODAPPLY"."ADDRESSID" IS '收货地址ID';

COMMENT ON COLUMN "REC_GOODAPPLY"."PICKCODE" IS '配送code：001=自提，002=配送';

COMMENT ON COLUMN "REC_GOODAPPLY"."AFFIRMGOODCODE" IS '提货审核状态：001=待审核 002=审核中 003=审核通过 004=审核失败';

COMMENT ON COLUMN "REC_GOODAPPLY"."GETGOODCODE" IS '提货状态：001=已申请，002=已发货，...';

COMMENT ON COLUMN "REC_GOODAPPLY"."CODENO" IS '编号';

COMMENT ON COLUMN "REC_GOODAPPLY"."CARNO" IS '车号';

COMMENT ON COLUMN "REC_GOODAPPLY"."LINKMAN" IS '联系人';

COMMENT ON COLUMN "REC_GOODAPPLY"."MOBPHONE" IS '手机：填写备用电话';

COMMENT ON COLUMN "REC_GOODAPPLY"."FAREID" IS '运费价格标准ID';

COMMENT ON COLUMN "REC_GOODAPPLY"."MEANUM" IS '重量';

COMMENT ON COLUMN "REC_GOODAPPLY"."MILNUM" IS '里程数';

COMMENT ON COLUMN "REC_GOODAPPLY"."PRICE" IS '运费';

COMMENT ON COLUMN "REC_GOODAPPLY"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_GOODAPPLY"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_GOODAPPLY"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_GOODAPPLY"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_GOODAPPLY"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_GOODAPPLY_ORDERGOOD"."ID" IS 'ID';

COMMENT ON COLUMN "REC_GOODAPPLY_ORDERGOOD"."GOODAPPLYID" IS '提货申请ID';

COMMENT ON COLUMN "REC_GOODAPPLY_ORDERGOOD"."ORDERGOODID" IS '订单商品ID';

COMMENT ON COLUMN "REC_GOODAPPLY_ORDERGOOD"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_GOODAPPLY_ORDERGOOD"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_GOODAPPLY_ORDERGOOD"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_GOODAPPLY_ORDERGOOD"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_GOODAPPLY_ORDERGOOD"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_GOODCHECK"."ID" IS 'ID';

COMMENT ON COLUMN "REC_GOODCHECK"."FRONTUSERID" IS '提货申请记录ID';

-- ALTER TABLE "REC_GOODCHECK" RENAME COLUMN "FRONTUSERID" TO "GOODAPPLYID";
COMMENT ON COLUMN "REC_GOODCHECK"."AFFIRMSTATUSCODE" IS '审核状态code：001=待审核 002=审核中 003=审核通过 004=审核失败';

COMMENT ON COLUMN "REC_GOODCHECK"."BACKUSERID" IS '审核人ID';

COMMENT ON COLUMN "REC_GOODCHECK"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_GOODCHECK"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_GOODCHECK"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_GOODCHECK"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_GOODTRACK"."ID" IS 'ID';

COMMENT ON COLUMN "REC_GOODTRACK"."FRONTUSERID" IS '提货申请记录ID';

-- ALTER TABLE "REC_GOODTRACK" RENAME COLUMN "FRONTUSERID" TO "GOODAPPLYID";
COMMENT ON COLUMN "REC_GOODTRACK"."CODENO" IS '编号';

COMMENT ON COLUMN "REC_GOODTRACK"."PROVCODE" IS '省code';

COMMENT ON COLUMN "REC_GOODTRACK"."CITYCODE" IS '市code';

COMMENT ON COLUMN "REC_GOODTRACK"."COUNTYCODE" IS '县code：具体位置可能没有县';

COMMENT ON COLUMN "REC_GOODTRACK"."ADDRESS" IS '详细地址';

COMMENT ON COLUMN "REC_GOODTRACK"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_GOODTRACK"."OPERATIONIP" IS '操作IP';

COMMENT ON COLUMN "REC_GOODTRACK"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_GOODTRACK"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_GOODTRACK"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_LOG"."ID" IS 'ID';

COMMENT ON COLUMN "REC_LOG"."MDLCODE" IS '模块code';

COMMENT ON COLUMN "REC_LOG"."TYPECODE" IS '操作类型code：001=增 002=删除 003=修改 004=查询';

COMMENT ON COLUMN "REC_LOG"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_LOG"."OPERATIONIP" IS '操作IP';

COMMENT ON COLUMN "REC_LOG"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_LOG"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_LOG"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_NEWS"."ID" IS 'ID';

COMMENT ON COLUMN "REC_NEWS"."NEWSCODE" IS '资讯类型code：001=主页，001001=往期活动，001002=聚化动态，001003=市场分析';

COMMENT ON COLUMN "REC_NEWS"."TITLE" IS '标题';

COMMENT ON COLUMN "REC_NEWS"."SHORT" IS '简介';

-- ALTER TABLE "REC_NEWS" RENAME COLUMN "SHORT" TO "SHORTNAME";
COMMENT ON COLUMN "REC_NEWS"."CONTENT" IS '内容';

COMMENT ON COLUMN "REC_NEWS"."AUTHOR" IS '作者';

COMMENT ON COLUMN "REC_NEWS"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_NEWS"."OPERATIONIP" IS '操作IP';

COMMENT ON COLUMN "REC_NEWS"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_NEWS"."UPDATETIME" IS '更新时间';

COMMENT ON COLUMN "REC_NEWS"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_NEWS"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_ORDER"."ID" IS 'ID';

COMMENT ON COLUMN "REC_ORDER"."ORDERNO" IS '订单号：规则未知';

COMMENT ON COLUMN "REC_ORDER"."FRONTUSERID" IS '客户ID';

COMMENT ON COLUMN "REC_ORDER"."ORDERSTATUSCODE" IS '订单状态code：001=已下单，002=商务支付，003=线下支付，002001=已付款，002002=已收款';

COMMENT ON COLUMN "REC_ORDER"."COLLECTIONID" IS '首款表ID';

COMMENT ON COLUMN "REC_ORDER"."PAYCODE" IS '支付方式ID：业务流程是下订单后再支付';

COMMENT ON COLUMN "REC_ORDER"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_ORDER"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_ORDER"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_ORDER"."SRCCODE" IS '来源单号code：001=购物车编号 002=单品上架单编号';

COMMENT ON COLUMN "REC_ORDER"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_ORDER_GOOD"."ID" IS 'ID';

COMMENT ON COLUMN "REC_ORDER_GOOD"."GOODID" IS '商品ID';

COMMENT ON COLUMN "REC_ORDER_GOOD"."ORDERID" IS '订单ID';

COMMENT ON COLUMN "REC_ORDER_GOOD"."RATE" IS '税率';

COMMENT ON COLUMN "REC_ORDER_GOOD"."TAXMONEY" IS '税额';

COMMENT ON COLUMN "REC_ORDER_GOOD"."PRICE" IS '成交价格';

COMMENT ON COLUMN "REC_ORDER_GOOD"."NUM" IS '购买数量';

COMMENT ON COLUMN "REC_ORDER_GOOD"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_ORDER_GOOD"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_ORDER_GOOD"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_ORDER_GOOD"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_ORDER_GOOD"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_ROLE_AUTH"."ID" IS 'ID';

COMMENT ON COLUMN "REC_ROLE_AUTH"."AUTHID" IS '权限ID';

COMMENT ON COLUMN "REC_ROLE_AUTH"."ROLEID" IS '角色ID';

COMMENT ON COLUMN "REC_ROLE_AUTH"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_SELL"."ID" IS 'ID';

COMMENT ON COLUMN "REC_SELL"."SUPID" IS '供应商ID';

COMMENT ON COLUMN "REC_SELL"."GOODID" IS '商品ID';

COMMENT ON COLUMN "REC_SELL"."CODENO" IS '编号：方便三方沟通';

COMMENT ON COLUMN "REC_SELL"."TITLE" IS '标题';

COMMENT ON COLUMN "REC_SELL"."CONTENT" IS '描述';

COMMENT ON COLUMN "REC_SELL"."LINKMAN" IS '联系人：供应商联系人，不一定是登录人';

COMMENT ON COLUMN "REC_SELL"."MOBPHONE" IS '手机';

COMMENT ON COLUMN "REC_SELL"."PHONE" IS '固话';

COMMENT ON COLUMN "REC_SELL"."PRICEBEGIN" IS '起拍价';

COMMENT ON COLUMN "REC_SELL"."PRICEPER" IS '最低加价：可选';

COMMENT ON COLUMN "REC_SELL"."PRICEONE" IS '一口价';

COMMENT ON COLUMN "REC_SELL"."PRICESUCC" IS '成交价';

COMMENT ON COLUMN "REC_SELL"."NUM" IS '数量：需要冻结库存数量';

COMMENT ON COLUMN "REC_SELL"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_SELL"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_SELL"."BEGINTIME" IS '开始时间';

COMMENT ON COLUMN "REC_SELL"."ENDTIME" IS '结束时间：成交时间<=结束时间，以此判断是否过期，???宜系统统一设定时间，则该字段无用';

COMMENT ON COLUMN "REC_SELL"."SUCCTIME" IS '成交时间';

COMMENT ON COLUMN "REC_SELL"."DEALCODE" IS '进展状态：001=已发布 002=已完成 003=已取消 004=已超时';

COMMENT ON COLUMN "REC_SELL"."MEMO" IS '备注';

-- ALTER TABLE "REC_SELLDET" DROP("TITLE");
COMMENT ON COLUMN "REC_SELLDET"."ID" IS 'ID';

COMMENT ON COLUMN "REC_SELLDET"."BUYID" IS '竞价采购ID';

COMMENT ON COLUMN "REC_SELLDET"."GUESTID" IS '客户ID：每个客户可以多次亮价';

COMMENT ON COLUMN "REC_SELLDET"."MOBPHONE" IS '手机';

COMMENT ON COLUMN "REC_SELLDET"."PHONE" IS '固话';

COMMENT ON COLUMN "REC_SELLDET"."PRICE" IS '价格：查账户余额，查商城最低价（若加价高于最低价，则提示买方）';

COMMENT ON COLUMN "REC_SELLDET"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_SELLDET"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_SELLDET"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_SELLDET"."STATUSCODE" IS '有效状态：001=有效 002=无效，对于恶意出价，可以屏蔽';

COMMENT ON COLUMN "REC_SELLDET"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_STOCK"."ID" IS 'ID';

COMMENT ON COLUMN "REC_STOCK"."GOODID" IS '商品ID';

COMMENT ON COLUMN "REC_STOCK"."FRONTSTOCKID" IS '卖家仓库ID';

COMMENT ON COLUMN "REC_STOCK"."NUM" IS '剩余数量：卖家、仓库、商品的余量';

COMMENT ON COLUMN "REC_STOCK"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_STOCK"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_STOCK"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_STOCK"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_STOCK"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_STOCKDET"."ID" IS 'ID';

COMMENT ON COLUMN "REC_STOCKDET"."STOCKID" IS '库存记录ID';

COMMENT ON COLUMN "REC_STOCKDET"."CODENO" IS '批号：卖方+仓库+商品下的批号（可能不同于实际的批号）规则???';

COMMENT ON COLUMN "REC_STOCKDET"."STOCKCODE" IS '库存类型code：001=入库、002=确认入库、003=上架、004=下架、005=出库、006=退货、007=其他';

COMMENT ON COLUMN "REC_STOCKDET"."NUM" IS '数量：一批次的入库、上架、下架、出库、退货或其他数量';

COMMENT ON COLUMN "REC_STOCKDET"."AFFIRMNUM" IS '确认数量：（后台）';

COMMENT ON COLUMN "REC_STOCKDET"."AFFIRMSTOCKCODE" IS '库存审核状态：只对应001=入库：001=待审核 002=审核中；003=审核通过；004=审核驳回';

COMMENT ON COLUMN "REC_STOCKDET"."PRODUCINGAREA" IS '产地';

COMMENT ON COLUMN "REC_STOCKDET"."PRODUCER" IS '生产商';

COMMENT ON COLUMN "REC_STOCKDET"."PACKTYPECODE" IS '包装类型code：001=木托，002=塑托，003=散货';

COMMENT ON COLUMN "REC_STOCKDET"."PACKCONTENT" IS '包装说明code：001=黑字，002=火炬';

COMMENT ON COLUMN "REC_STOCKDET"."PAYCODE" IS '支付方式code：例如：002=线下支付，002001=现金、002002=电汇等';

COMMENT ON COLUMN "REC_STOCKDET"."PRICE" IS '价格';

COMMENT ON COLUMN "REC_STOCKDET"."RATE" IS '税率';

COMMENT ON COLUMN "REC_STOCKDET"."TAXMONEY" IS '税额';

COMMENT ON COLUMN "REC_STOCKDET"."FINALMONEY" IS '价税合计';

COMMENT ON COLUMN "REC_STOCKDET"."FAREID" IS '运费价格标准ID';

COMMENT ON COLUMN "REC_STOCKDET"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_STOCKDET"."OPERATIONIP" IS '操作IP';

COMMENT ON COLUMN "REC_STOCKDET"."CREATETIME" IS '创建世间：对应库存类型的各种时间';

COMMENT ON COLUMN "REC_STOCKDET"."STATUSCODE" IS '有效状态code：001=有效 002=无效';

COMMENT ON COLUMN "REC_STOCKDET"."MEMO1" IS '备注1';

COMMENT ON COLUMN "REC_STOCKDET"."MEMO2" IS '备注2';

COMMENT ON COLUMN "REC_STOCKDET"."MEMO3" IS '备注3';

COMMENT ON COLUMN "REC_STOCKDET"."MEMO4" IS '备注4';

COMMENT ON COLUMN "REC_STOCKDET"."MEMO5" IS '备注5';

COMMENT ON COLUMN "REC_STOCKDET_ORDERGOOD"."ID" IS 'ID';

COMMENT ON COLUMN "REC_STOCKDET_ORDERGOOD"."STOCKID" IS '库存明细ID';

-- ALTER TABLE "REC_STOCKDET_ORDERGOOD" RENAME COLUMN "STOCKID" TO "STOCKDETID";
COMMENT ON COLUMN "REC_STOCKDET_ORDERGOOD"."ORDERGOODID" IS '订单_商品ID';

COMMENT ON COLUMN "REC_STOCKDET_ORDERGOOD"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_STOCKDET_ORDERGOOD"."OPERATIONIP" IS '操作IP';

COMMENT ON COLUMN "REC_STOCKDET_ORDERGOOD"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_STOCKDET_ORDERGOOD"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_STOCKDET_ORDERGOOD"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_TAXHIS"."ID" IS 'ID';

COMMENT ON COLUMN "REC_TAXHIS"."STOCKDETID" IS '库存明细ID';

COMMENT ON COLUMN "REC_TAXHIS"."RATE" IS '税率：历史税率';

COMMENT ON COLUMN "REC_TAXHIS"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_TAXHIS"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_TAXHIS"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_TAXHIS"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_TAXHIS"."MEMO" IS '备注';

COMMENT ON COLUMN "REC_VIRTUALACCOUNT"."ID" IS 'ID';

COMMENT ON COLUMN "REC_VIRTUALACCOUNT"."BANKCODE" IS '银行code：聚化网平台账户所属银行（目前只有日行、中行）';

COMMENT ON COLUMN "REC_VIRTUALACCOUNT"."COMPANYID" IS '客户公司ID：当类型code=001平台，该字段为null';

COMMENT ON COLUMN "REC_VIRTUALACCOUNT"."ACCOUNTCODE" IS '虚拟账户类型code：001=平台，002=买家，003=卖家';

COMMENT ON COLUMN "REC_VIRTUALACCOUNT"."VIRTUALACCOUNT" IS '虚拟账号';

COMMENT ON COLUMN "REC_VIRTUALACCOUNT"."TOTALMONEY" IS '余额';

COMMENT ON COLUMN "REC_VIRTUALACCOUNT"."OPERATIONID" IS '操作人ID';

COMMENT ON COLUMN "REC_VIRTUALACCOUNT"."OPERATIONIP" IS '操作人IP';

COMMENT ON COLUMN "REC_VIRTUALACCOUNT"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "REC_VIRTUALACCOUNT"."STATUSCODE" IS '有效状态：001=有效 002=无效';

COMMENT ON COLUMN "REC_VIRTUALACCOUNT"."MEMO" IS '备注';

